name: Test
"on":
  push:
    branches:
      - dependabot/npm_and_yarn/**
  pull_request:
    types:
      - opened
      - synchronize
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version:
          - 10
          - 12
          - 14
    steps:
      - uses: actions/checkout@v2
      - name: "Use Node.js ${{ matrix.node_version }}"
        uses: actions/setup-node@v1
        with:
          node-version: "${{ matrix.node_version }}"
      - run: npm ci
      - run: npm test
 804.5nm.
Objects:
    ---------------------------------------------------------------------
       RA   (2000)   DE    Designation(s)                 (File)
    ---------------------------------------------------------------------
    16 55 35.7 -08 23 36   VB 8 = LHS 429 = Gl 644 C      (vb8.dat)
    08 53 36   -03 29 30   LHS 2065 = LP 666-9            (lhs2065.dat)
    03 39 34.6 -35 25 51   LP 944-20                      (lp944-20.dat)
    05 45 59.9 -32 18 23   µ Col = HR 1996 = HD 38666  (mucol.dat)
    ---------------------------------------------------------------------

File Summary:

       FileName      Lrecl  Records   Explanations

ReadMe            80        .   This file
vb8.dat           26    14390   Spectrum for VB8
lhs2065.dat       26    14390   Spectrum for LHS2065
lp944-20.dat      26    14390   Spectrum for LP944-20
mucol.dat         23    14390   Atmospheric Spectrum for Mu Columbae


Byte-by-byte Description of file: vb8.dat, lhs2065.dat, lp944-20.dat

   Bytes Format   Units  Label     Explanations

   1- 12  F12.2   0.1nm  Lambda    Central wavelength of the flux bin
  13- 26  A14     mJy    Fnu       Data in interorder gaps has value 0.0


Byte-by-byte Description of file: mucol.dat

   Bytes Format   Units  Label     Explanations

   1- 12  F12.2   0.1nm  Lambda    Central wavelength of the flux bin
  13- 23  F11.6   ---    Fnu      *Data in interorder gaps has value 0.0

Note on Fnu:
  mJy which have been normalised to value 1.0
  in the continuum of the atmospheric standard star

(End)
